### ISSUE TITLE
プリント基板を扱う

### ISSUE THREAD

**Issue by makki0205** [HAL-RO-Developer/iot_plat_doc#16]
# 背景
デバイスの小型化や見た目を良くするために
プリント基板を扱う
# 目的
プリント基板の切削機を自在に扱えるようにする
# 対応内容
1. ロボラボの切削機を調査
2. 必要Softwareのインストール
3. 実際に削るためのテスト基盤を作成する。
# 期日
6/10

**Comment by yam123** [comment]
##調査結果
- 開発環境をインストールしなくても、ロボラボにあるPCに準備が整っていました。
- PCBは個人PCにあればいいです。
- 基盤削りの近くに緑のファイルがあるので、それを参照したら全部あります。

## 実際に削った結果
- LEDと抵抗の回路を削りました。
- 穴は空けたけどまだ調査が必要です。あと何回かテストしたらできそうです。

以上
