### ISSUE TITLE
groveモジュールの購入リストを作成

### ISSUE THREAD

**Issue by makki0205** [HAL-RO-Developer/iot_plat_doc#18]
# 背景
はやめにgrovemoduleの購入しないと届くまでに時間がかかる可能性があるため
# 目的
groveデバイスの購入リストをgoogleスプレットシートに作成しリンクをここに貼る
# 対応内容
物品購入リストを作成する
# 期日
6/7

**Comment by RikuHashimoto** [comment]
https://docs.google.com/spreadsheets/d/1-Ulrki6QmyQ7Xmya1lS_s5LOVza3R5QLYV9l6pieGQ4/edit#gid=0

**Comment by makki0205** [comment]
ありがとうございます！

**Comment by RikuHashimoto** [comment]
Grove モジュール届きました
