### ISSUE TITLE
Analog入力の時間調査

### ISSUE THREAD

**Issue by Komei1009** [HAL-RO-Developer/iot_plat_doc#25]
# 背景
Analog値を扱うため
# 目的
応答速度の要求を満たすため
# 対応内容
- アナログ値取得のソースコード添付
- かかった時間のシリアルモニター添付
# 期日
6/19

**Comment by RikuHashimoto** [comment]
unsigned long t1;
unsigned long t2;
void setup() {
 Serial.begin(115200);
}

void loop() {
t1 = micros();
analogRead(A0);
t2 = micros();
Serial.println(t2-t1);
delay(1000);
}

コンソール結果
190
184
172
166
174
185
187
156
186
193
161
153
166
182
172
194
174
166
