### ISSUE TITLE
PWM出力

### ISSUE THREAD

**Issue by Komei1009** [HAL-RO-Developer/iot_plat_doc#26]
# 背景
PWM出力を行うため
# 目的
PWM出力を作品制作時に容易に行うようにするため
# 対応内容
- フルカラーLEDを赤色→黄色→緑色→水色→青色→紫色の順に変化させる。
- 作成したソースコードの添付(コメントは可能な限り細かく記述)
# 期日
6/21

**Comment by RikuHashimoto** [comment]
int val;
int LEDpin = 5;
void setup() {

}

void loop() {
  /* だんだん明るく*/
  for(val=0; val <255;val+=5){
analogWrite(LEDpin,val);
delay(100);
  }
    /* だんだん暗く*/
    for(val=255; val>0;val-=5){
analogWrite(LEDpin,val);
delay(100);
  }
}


回路は
LEDのアノードをESP8266のD1
カソードをGNDに繋いでます

**Comment by RikuHashimoto** [comment]
analogWriteの応答時間は27μsです
