### ISSUE TITLE
Groveモジュールの調査(音センサ)

### ISSUE THREAD

**Issue by Komei1009** [HAL-RO-Developer/iot_plat_doc#29]
# 背景
Groveモジュールを使用するため
# 目的
Groveモジュールの仕様を明確にするため
# 対応内容
- 音センサの応答時間
- 制御できる精度の調査(証拠添付)
# 期日
6/28

**Comment by RikuHashimoto** [comment]
unsigned int val;
unsigned long t1;
unsigned long t2;
void setup() {
 Serial.begin(115200);
}

void loop() {
t1 = micros();
val = analogRead(A0);
t2 = micros();
if(val != 0){
Serial.print("val=");
Serial.print(val);
Serial.print(" time=");
Serial.println(t2-t1);
}
delay(500);
}

Serial結果 valは音の大きさ timeは応答速度で単位がμs
val=446 time=157
val=595 time=186
val=753 time=170
val=681 time=174
val=153 time=153
val=213 time=183
val=126 time=205
val=393 time=190
val=446 time=157
val=595 time=186
val=753 time=170
val=681 time=174
val=153 time=153
val=213 time=183
val=126 time=205
val=393 time=190

※このモジュールの電源電圧が4～12V(標準5V)です
　ESP8266のvinから電源を取ろうとした所ずっとアナログ値が0のままだったので
　vinからの電圧を測ってみた所4.7Vでした。5Vの外部電源に変えたら検出するようになりましたが
　iPhoneから音楽を流しても、スピーカー部分をモジュールにかなり近づけないとちゃんと検出されい
（音楽を流しても10～25しか出ない)ので大きな外部電源が必要かもしれないです。
