### ISSUE TITLE
Groveモジュールの調査(光センサー)

### ISSUE THREAD

**Issue by Komei1009** [HAL-RO-Developer/iot_plat_doc#30]
# 背景
Groveモジュールを使用するため
# 目的
Groveモジュールの仕様を明確にするため
# 対応内容
- 光センサーの応答時間
- 制御できる精度の調査(証拠添付)
# 期日
6/28

**Comment by RikuHashimoto** [comment]
unsigned int val;
unsigned long t1;
unsigned long t2;
void setup() {
 Serial.begin(115200);
}

void loop() {
t1 = micros();
val = analogRead(A0);
t2 = micros();
Serial.print("val=");
Serial.print(val);
Serial.print(" time=");
Serial.println(t2-t1);
delay(1000);
}

応答時間は160～200μs

**Comment by RikuHashimoto** [comment]
明るさは普通の状態で300～700ほど
iPhoneのライトを5cmぐらい離れて当てると1024
手で軽く覆うと100～150ぐらい出ます

**Comment by RikuHashimoto** [comment]
配線は
センサーのVCCをマイコンのGND
 GNDをGND
SIGをA0
NCは接続なし
です
