### ISSUE TITLE
Groveモジュールの調査(デジタル温度・湿度)

### ISSUE THREAD

**Issue by Komei1009** [HAL-RO-Developer/iot_plat_doc#31]
# 背景
Groveモジュールを使用するため
# 目的
Groveモジュールの仕様を明確にするため
# 対応内容
- デジタル温度・湿度の取得時間
- 制御できる精度の調査(証拠添付)
# 期日
6/28

**Comment by show-t** [comment]
Groveの温度・湿度センサーは独自の1wire通信を行って値を取得している。
汎用性がないため、ライブラリを使用する。
（参考）http://www.geocities.jp/zattouka/GarageHouse/micon/Arduino/Humidity/Humidity.htm

[PIN-ASSIGN]
GND[Black] - GND
Vcc[Red] - 3V3
NC[White] - 未接続
SIG[Yellow] - D5
