### ISSUE TITLE
ESP8266のコンポーネントをDesignSparkPCB等で作成する

### ISSUE THREAD

**Issue by yam123** [HAL-RO-Developer/iot_plat_doc#34]
# 背景
電気回路を組むためにESP8266のボードをPCBで作成する。
DesignSparkやLTSpiceのGridの幅はブレッドボードの穴の幅と同じなので、以下ドットとして書きます。

ESP8266のサイズ
- 横 12ドット
- 縦 10ドット
- PINを配置するのにドットとピッタリではなく、すこし幅を開ける
# 目的
デバイスの電気回路やテストを行えるため。
# 対応内容
完成物の画像とデータを上げる
# 期日
6/30

**Comment by yam123** [comment]
まだ未完成です。

原因：Ｊkenへの勉強やアルバイトで作業する時間を作れなかった。
対策：バイトの時間を再調整し、作業する時間を作る。

**Comment by RikuHashimoto** [comment]
![12](https://user-images.githubusercontent.com/29031481/27717100-d9bf110a-5d7d-11e7-8746-b9e9007da313.png)
![13](https://user-images.githubusercontent.com/29031481/27717098-d9b2436c-5d7d-11e7-82f3-91684cd62968.png)

**Comment by RikuHashimoto** [comment]
https://drive.google.com/file/d/0B8kiuN-BwfKBUnZFdkotcXE4aFE/view?usp=sharing
