### ISSUE TITLE
バッテリーの出力電圧調査

### ISSUE THREAD

**Issue by yam123** [HAL-RO-Developer/iot_plat_doc#37]
# 背景

# 目的
バッテリーの電圧によって作る回路が変わるから

# 対応内容
バッテリーからどれぐらい電圧が出てくるか調査する。
結果次第、降圧の回路を組まないといけなくなる。

# 期日
6/20

**Comment by RikuHashimoto** [comment]
![img_1012](https://user-images.githubusercontent.com/29031481/27335169-95aa58ae-5606-11e7-8f65-6f97d0ef23fb.JPG)

3.9V出ました

**Comment by RikuHashimoto** [comment]
![img_1011](https://user-images.githubusercontent.com/29031481/27335399-39326a02-5607-11e7-8725-8a806902695d.JPG)
電流は220Ωの抵抗を挟んで20mA出ました
