### ISSUE TITLE
GROVEモジュールを1PINで制御できるか

### ISSUE THREAD

**Issue by yam123** [HAL-RO-Developer/iot_plat_doc#40]
# 背景
デジタルポートに2PINずつではPIN数が足りない為、1PINで制御できるかの調査。
# 目的
1PINで制御できれば2PIN余ることでフルカラーLEDと電源→モジュール間のスイッチができる
# 対応内容
全GROVEモジュールが1PINで制御できるかどうか
今Assigneesの方々が各モジュールを持っていると思い、調査しながら持っているモジュールを1PINで制御して見てください。現時点でモジュールが1PINだけで制御しているやつはコメントでお知らせください。
宜しくお願いします。
# 期日
06/22

**Comment by teruya002** [comment]
![dsc_0002](https://user-images.githubusercontent.com/28592885/27425416-5465524a-5773-11e7-85ea-1f93b998662c.JPG)

上の写真の様な状態を指しているのならばこれでも制御は可能でした。
黒 GND
赤 Vcc(5V)
白 未接続
黄 Digital 6Pin
上記配線でもブザーのプログラムは問題なく動きました。

**Comment by RikuHashimoto** [comment]
音センサと光センサは1ピンと電源だけで動きます

**Comment by hiyanaka** [comment]
赤外線送信・受信モジュールともに1pinのみで制御可能
- 共通
赤 Vcc(5v or 3.3v)
黒 GND
白 NC(未接続)
- 赤外線送信モジュール
黄 Tx(送信)
- 赤外線受信モジュール
黄 Rx(受信)

**Comment by makki0205** [comment]
1PINにしてしまうと以下の問題が発生します
- uartが使えない
- 赤外線送信moduleと受信moduleはコネクトpinのは配置が違うためどちらかが使用不可になる
- アルコールセンサ等の諸々のモジュールが利用できなくなる

なので却下させていただきます。

それならデジタルPIN減らして
- I2C ×2
- デジタルPIN ×1
- アナログPIN ×1
