### ISSUE TITLE
ハードウェア基盤のサイズ決定

### ISSUE THREAD

**Issue by Komei1009** [HAL-RO-Developer/iot_plat_doc#43]
# 背景
サイズが決定しなければ、メカの作業が進まないため
# 目的

# 対応内容
ハードウェア担当とメカトロニクス担当の話し合いで確保しなければならないサイズを決定する。
# 期日
6/29

**Comment by yam123** [comment]
ハードの基板サイズ

ＩＣＯＣＡイメージで
縦    = 55mm
横    = 85mm
高さ = 25mm

の2層で作る予定です。画像は後程作成します
