### ISSUE TITLE
デバイスの外装寸法決定

### ISSUE THREAD

**Issue by Komei1009** [HAL-RO-Developer/iot_plat_doc#44]
# 背景

# 目的

# 対応内容
- デバイスを格納する外装寸法の決定。
- 配線に必要な余剰部分の話し合いをメカトロ担当とハードウェア担当で行う。
# 期日
7/4

**Comment by teruya002** [comment]
横=87mm
縦=57mm
高さ=35mm
として仮設定中
今後細かく変動する可能性有
