### ISSUE TITLE
降圧昇圧のテスト

### ISSUE THREAD

**Issue by yam123** [HAL-RO-Developer/iot_plat_doc#60]
# 背景
回路作成を簡単にするため

# 目的

# 対応内容
DC-DCコンバータの電子パーツを使って目的の電圧にできるか

- できた場合：同じ物の昇圧バージョンや昇圧バージョンも購入。
- できなかった場合：降圧昇圧回路を組む。

# 期日
7/3

**Comment by yam123** [comment]
[使用するDC-DCコンバーター](http://eleshop.jp/shop/g/gDAN413/)

テスト用で部品を2個購入しました。
明日までにテストを終わらせたいと思います。

**Comment by teruya002** [comment]
https://www.plexim.com/ja/academy/power-electronics/buck-conv
分圧を使いましたがこれでいけました。

**Comment by teruya002** [comment]
![screenshot_2017-07-13-16-56-31](https://user-images.githubusercontent.com/28592885/28156277-0bb55740-67ed-11e7-93c1-2e457f798e41.png)
降圧テスト（分圧）結果です

**Comment by yam123** [comment]
[昇圧回路.asc](https://drive.google.com/drive/folders/0B-DrtusZsmgaWGdDR3Uwdlc1STA)

![default](https://user-images.githubusercontent.com/20219162/28159888-6b5a866e-67f9-11e7-88c4-18b43e3e92bc.png)

昇圧回路図です。
