### ISSUE TITLE
フルカラーLEDの調査及び選定

### ISSUE THREAD

**Issue by makki0205** [HAL-RO-Developer/iot_plat_doc#9]
ステータスランプのフルカラーLEDの調査及び選定

1. 調査
2. 選定
3. 購入
4. 実装

作業がおひとつ終わるごとに何かしらの成果物をissuesのコメントに貼ってください。

**Comment by teruya002** [comment]
項目1の調査については秋月電子のHPを見て調べました。
項目２の選定については5mmΦのフルカラーの中からICが内蔵されていない４本足のタイプとして見たところ１つしか種類がない状況です。
項目３についてはこの秋月のものにする場合最低でも２日は注文してから届くのに時間がかかる都合上明日中に購入する事はできません。
項目４については３が達成不能なため同じく明日することができません。
４つ一気に報告する形になってすみません。

**Comment by makki0205** [comment]
購入予定のLEDのURLを貼ってください
それで２まで完了と致します

期日はそれを対応後決めます

**Comment by teruya002** [comment]
http://akizukidenshi.com/catalog/g/gI-02476/
これです。

**Comment by makki0205** [comment]
@RikuHashimoto が購入してくれたので受け取ってサンプルコードの作成を勧めてください。

**Comment by makki0205** [comment]
## サンプルコードは
- led(red,green,blue);でledがフルカラーで表現できる関数を作成する
- 回路を写メでissueに貼る

**Comment by teruya002** [comment]
中間報告
![dsc_0002](https://user-images.githubusercontent.com/28592885/26838049-fe1cd544-4b19-11e7-8e77-f45ac4482137.JPG)
関数を使ってのフルカラーLEDは現在できていませんが、回路はできたので先に送っておきます

**Comment by teruya002** [comment]
```sh
#include "fullLED.h"
void setup() {
  pinMode(9,OUTPUT);
  pinMode(10,OUTPUT);
  pinMode(11,OUTPUT);
}

void loop()
{
  void led(uint8_t red,uint8_t green,uint8_t blue);
{
  int red=9;
  int green=10;
  int blue=11;
  analogWrite(red,255);
  analogWrite(green,0);
  delay(1000);

  analogWrite(green,255);
  analogWrite(blue,0);
  delay(1000);
  
  analogWrite(red,0);
  analogWrite(blue,255);
  delay(1000);
}
}

//自作ヘッダファイル
#ifndef fullLED_H_INCLUDED
#define fullLED_H_INCLUDED

void led(uint8_t red,uint8_t green,uint8_t blue);

#endif
```
関数化のプログラミングと今回の授業で成功したフルカラー点灯の回路図です。

**Comment by teruya002** [comment]
![dsc_0003](https://user-images.githubusercontent.com/28592885/26876468-509be6dc-4bc1-11e7-9f68-3bd83e7777f0.JPG)

**Comment by teruya002** [comment]
追記：上記の写真での抵抗の値はR:300Ω G:82Ω B:82Ωでやっています。

**Comment by makki0205** [comment]
問題なし 〆
